name: Test API Endpoints

on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Fix permissions for Jest
        run: chmod +x node_modules/.bin/jest

      - name: Start server
        run: |
          node server.js &
          sleep 5  # Aumente o tempo se necessário para garantir que o servidor inicie

      - name: Run all tests in the 'teste' folder
        run: |
          npx jest teste/getAllCharacters.spec.js --coverage --passWithNoTests --verbose
          npx jest teste/getPlanetNotFound.spec.js --coverage --passWithNoTests --verbose
          npx jest teste/planetByName.spec.js --coverage --passWithNoTests --verbose
          npx jest teste/swapi.spec.js --coverage --passWithNoTests --verbose
          npx jest teste/validateCharacterData.spec.js --coverage --passWithNoTests --verbose
          npx jest teste/validatePlanetData.spec.js --coverage --passWithNoTests --verbose
          npx jest teste/getAllPlanets.spec.js --coverage --passWithNoTests --verbose
          npx jest teste/getAllPlanetsCount.spec.js --coverage --passWithNoTests --verbose
          npx jest teste/getCharacterNotFound.spec.js --coverage --passWithNoTests --verbose
          npx jest teste/planetByName.spec.js --coverage --passWithNoTests --verbose
