name: Test API Endpoints

on: [push, pull_request]

jobs:
  test-get-all-characters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start server in the background
        run: |
          nohup node server.js &
          sleep 5 # Ajuste o tempo se necessário

      - name: Run test for getAllCharacters
        run: npx jest teste/getAllCharacters.spec.js --coverage

  test-get-all-characters-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start server in the background
        run: |
          nohup node server.js &
          sleep 5

      - name: Run test for getAllCharactersCount
        run: npx jest teste/getAllCharactersCount.spec.js --coverage

  test-get-all-planets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start server in the background
        run: |
          nohup node server.js &
          sleep 5

      - name: Run test for getAllPlanets
        run: npx jest teste/getAllPlanets.spec.js --coverage

  test-get-all-planets-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start server in the background
        run: |
          nohup node server.js &
          sleep 5

      - name: Run test for getAllPlanetsCount
        run: npx jest teste/getAllPlanetsCount.spec.js --coverage

  test-get-character-not-found:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start server in the background
        run: |
          nohup node server.js &
          sleep 5

      - name: Run test for getCharacterNotFound
        run: npx jest teste/getCharacterNotFound.spec.js --coverage

  test-get-planet-not-found:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start server in the background
        run: |
          nohup node server.js &
          sleep 5

      - name: Run test for getPlanetNotFound
        run: npx jest teste/getPlanetNotFound.spec.js --coverage

  test-planet-by-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start server in the background
        run: |
          nohup node server.js &
          sleep 5

      - name: Run test for planetByName
        run: npx jest teste/planetByName.spec.js --coverage

  test-swapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start server in the background
        run: |
          nohup node server.js &
          sleep 5

      - name: Run test for swapi
        run: npx jest teste/swapi.spec.js --coverage

  test-validate-character-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start server in the background
        run: |
          nohup node server.js &
          sleep 5

      - name: Run test for validateCharacterData
        run: npx jest teste/validateCharacterData.spec.js --coverage

  test-validate-planet-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start server in the background
        run: |
          nohup node server.js &
          sleep 5

      - name: Run test for validatePlanetData
        run: npx jest teste/validatePlanetData.spec.js --coverage
